<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            // ── AKUNTANSI ──────────────────────────
            [
                'slug' => 'praktikum-akuntansi-sak-emkm',
                'title' => 'Praktikum Akuntansi SAK EMKM',
                'description' => 'Praktikum Akuntansi Sesuai SAK EMKM (10 Sesi)',
                'full_description' => 'Kelas ini mempersiapkan peserta untuk siap menghadapi tantangan dunia industri khususnya di bidang akuntansi. Materi mencakup siklus akuntansi lengkap, pembuatan laporan keuangan, dan praktik langsung dengan software.',
                'price' => 150000,
                'sessions' => 10,
                'quota' => 20,
                'schedule' => 'Fleksibel',
                'time' => '19.00 - Selesai',
                'level' => 'semua',
                'category' => 'akuntansi',
                'instructor' => 'M. Aziz Andriansyah, S.Pd., CAAT., CAP., CTTr',
                'rating' => 4.9,
                'students' => 45,
                'image' => '/images/courses/courseone.png',
                'benefits' => ['Relasi & Networking', 'Ilmu yang Bermanfaat', 'Konsultasi Tutor', 'E-Modul', 'Sertifikat'],
                'includes' => ['Video Pembelajaran', 'Live via Zoom', 'WhatsApp Group'],
                'is_popular' => true,
            ],
            [
                'slug' => 'akuntansi-dasar',
                'title' => 'Akuntansi Dasar',
                'description' => 'Mempelajari konsep dasar akuntansi keuangan',
                'full_description' => 'Kelas untuk pemula yang ingin memahami persamaan dasar akuntansi, siklus akuntansi, dan penyusunan laporan keuangan dasar.',
                'price' => 30000,
                'sessions' => 5,
                'quota' => 30,
                'schedule' => 'Fleksibel',
                'time' => '19.00 - Selesai',
                'level' => 'pemula',
                'category' => 'akuntansi',
                'instructor' => 'M. Aziz Andriansyah, S.Pd., CAAT., CAP., CTTr',
                'rating' => 4.8,
                'students' => 60,
                'image' => '/images/courses/coursetwo.png',
                'benefits' => ['E-Modul', 'Sertifikat', 'Konsultasi'],
                'includes' => ['Video Pembelajaran'],
            ],
            [
                'slug' => 'akuntansi-lanjutan',
                'title' => 'Akuntansi Lanjutan',
                'description' => 'Pembahasan akuntansi tingkat menengah hingga mahir',
                'full_description' => 'Lanjutan dari kelas dasar, mencakup akuntansi perusahaan dagang, manufaktur, dan analisis rasio keuangan.',
                'price' => 35000,
                'sessions' => 5,
                'quota' => 30,
                'schedule' => 'Fleksibel',
                'time' => '19.00 - Selesai',
                'level' => 'menengah',
                'category' => 'akuntansi',
                'instructor' => 'M. Aziz Andriansyah, S.Pd., CAAT., CAP., CTTr',
                'rating' => 4.8,
                'students' => 40,
                'image' => '/images/courses/coursethree.png',
                'benefits' => ['E-Modul', 'Sertifikat', 'Studi Kasus'],
                'includes' => ['Video Pembelajaran', 'Grup Diskusi'],
            ],

            // ── ACCURATE ──────────────────────────
            [
                'slug' => 'praktikum-komputer-akuntansi-accurate-online',
                'title' => 'Praktikum Komputer Akuntansi Accurate Online',
                'description' => 'Praktik menggunakan Accurate Online untuk pencatatan akuntansi digital',
                'full_description' => 'Pelatihan penggunaan software Accurate Online mulai dari setup awal database hingga cetak laporan keuangan.',
                'price' => 35000,
                'sessions' => 5,
                'quota' => 20,
                'schedule' => 'Fleksibel',
                'time' => '19.00 - Selesai',
                'level' => 'pemula',
                'category' => 'accurate',
                'instructor' => 'M. Aziz Andriansyah, S.Pd., CAAT., CAP., CTTr',
                'rating' => 4.8,
                'students' => 42,
                'image' => '/images/courses/courseone.png',
                'benefits' => ['Akses Trial Accurate', 'Praktik Langsung', 'E-Modul', 'Sertifikat'],
                'includes' => ['Video Tutorial', 'Panduan PDF'],
                'is_popular' => true,
            ],
            [
                'slug' => 'praktikum-komputer-akuntansi-accurate-online-profesional',
                'title' => 'Praktikum Komputer Akuntansi Accurate Online Profesional',
                'description' => 'Penggunaan tingkat mahir Accurate Online',
                'full_description' => 'Pelatihan tingkat mahir penggunaan Accurate Online untuk menangani kasus akuntansi yang lebih kompleks.',
                'price' => 50000,
                'sessions' => 8,
                'quota' => 15,
                'schedule' => 'Fleksibel',
                'time' => '19.00 - Selesai',
                'level' => 'mahir',
                'category' => 'accurate',
                'instructor' => 'M. Aziz Andriansyah, S.Pd., CAAT., CAP., CTTr',
                'rating' => 4.9,
                'students' => 25,
                'image' => '/images/courses/coursetwo.png',
                'benefits' => ['Advanced Cases', 'Sertifikat Profesional'],
                'includes' => ['Video Tutorial', 'Studi Kasus', 'Zoom Meeting'],
            ],
            [
                'slug' => 'praktikum-komputer-akuntansi-accurate-5-basic',
                'title' => 'Praktikum Komputer Akuntansi Accurate 5 Basic',
                'description' => 'Dasar-dasar penggunaan software desktop Accurate 5',
                'full_description' => 'Pengenalan dan penggunaan dasar software Accurate 5 versi desktop untuk UKM dan perusahaan.',
                'price' => 20000,
                'sessions' => 4,
                'quota' => 50,
                'schedule' => 'Fleksibel',
                'time' => 'Fleksibel',
                'level' => 'pemula',
                'category' => 'accurate',
                'instructor' => 'M. Aziz Andriansyah, S.Pd., CAAT., CAP., CTTr',
                'rating' => 4.7,
                'students' => 80,
                'image' => '/images/courses/coursethree.png',
                'benefits' => ['Ilmu Dasar', 'E-Modul', 'Sertifikat'],
                'includes' => ['Video Tutorial'],
            ],
            [
                'slug' => 'praktikum-komputer-akuntansi-accurate-5',
                'title' => 'Praktikum Komputer Akuntansi Accurate 5',
                'description' => 'Pelatihan komprehensif Accurate 5',
                'full_description' => 'Mempelajari semua modul standar di Accurate 5 dari setup hingga penutupan bulan.',
                'price' => 35000,
                'sessions' => 6,
                'quota' => 30,
                'schedule' => 'Fleksibel',
                'time' => 'Fleksibel',
                'level' => 'menengah',
                'category' => 'accurate',
                'instructor' => 'M. Aziz Andriansyah, S.Pd., CAAT., CAP., CTTr',
                'rating' => 4.8,
                'students' => 50,
                'image' => '/images/courses/courseone.png',
                'benefits' => ['Studi Kasus', 'E-Modul Lengkap', 'Sertifikat'],
                'includes' => ['Video Tutorial'],
            ],

            // ── EXCEL ──────────────────────────
            [
                'slug' => 'microsoft-excel',
                'title' => 'Microsoft Excel',
                'description' => 'Penguasaan Excel untuk bisnis dan perkantoran',
                'full_description' => 'Pelajari penggunaan Excel mulai dari rumus dasar hingga pengelolaan data tingkat lanjut',
                'price' => 10000,
                'sessions' => 5,
                'quota' => 100,
                'schedule' => 'Fleksibel',
                'time' => 'Fleksibel',
                'level' => 'semua',
                'category' => 'excel',
                'instructor' => 'M. Aziz Andriansyah, S.Pd., CAAT., CAP., CTTr',
                'rating' => 4.9,
                'students' => 120,
                'image' => '/images/courses/coursetwo.png',
                'benefits' => ['Template Excel', 'Sertifikat'],
                'includes' => ['Video Tutorial', 'Template'],
            ],

            // ── PAJAK ──────────────────────────
            [
                'slug' => 'perpajakan-dasar',
                'title' => 'Perpajakan Dasar',
                'description' => 'Pengetahuan dasar perpajakan Indonesia',
                'full_description' => 'Pelajari dasar-dasar perpajakan seperti KUP, PPh 21, dan sistem pelaporan pajak sederhana.',
                'price' => 35000,
                'sessions' => 5,
                'quota' => 30,
                'schedule' => 'Fleksibel',
                'time' => 'Fleksibel',
                'level' => 'pemula',
                'category' => 'pajak',
                'instructor' => 'M. Aziz Andriansyah, S.Pd., CAAT., CAP., CTTr',
                'rating' => 4.8,
                'students' => 40,
                'image' => '/images/courses/coursethree.png',
                'benefits' => ['Materi Pajak', 'Sertifikat'],
                'includes' => ['Video Tutorial'],
            ],
            [
                'slug' => 'perpajakan-lanjutan',
                'title' => 'Perpajakan Lanjutan',
                'description' => 'Studi kasus perpajakan untuk perusahaan',
                'full_description' => 'Lanjutan materi perpajakan seperti PPN, PPh Badan, dan ekualisasi pajak.',
                'price' => 50000,
                'sessions' => 6,
                'quota' => 20,
                'schedule' => 'Fleksibel',
                'time' => 'Fleksibel',
                'level' => 'menengah',
                'category' => 'pajak',
                'instructor' => 'M. Aziz Andriansyah, S.Pd., CAAT., CAP., CTTr',
                'rating' => 4.9,
                'students' => 25,
                'image' => '/images/courses/courseone.png',
                'benefits' => ['Studi Kasus Pajak', 'Sertifikat'],
                'includes' => ['Video Tutorial'],
            ],

            // ── PRODUK / BUKU ──────────────────────────
            [
                'slug' => 'buku-praktikum-komputer-akuntansi-accurate-5',
                'title' => 'Buku Praktikum Komputer Akuntansi Accurate 5',
                'description' => 'Buku fisik - Dasar-dasar akuntansi untuk perusahaan jasa dengan SAK EMKM dilengkapi studi kasus',
                'full_description' => 'Buku Cetak Fisik: Buku Praktikum Komputer Akuntansi "Accurate Accounting Versi 5". Membahas dasar-dasar akuntansi untuk perusahaan jasa dengan SAK EMKM yang dilengkapi dengan berbagai studi kasus relevan untuk latihan.',
                'price' => 75000, // Estimasi harga buku (belum disebutkan, asumsikan 75k)
                'sessions' => 0,
                'quota' => 100,
                'schedule' => '-',
                'time' => '-',
                'level' => 'semua',
                'category' => 'buku',
                'instructor' => 'M. Aziz Andriansyah, S.Pd.',
                'rating' => 5.0,
                'students' => 200,
                'image' => '/images/courses/coursetwo.png',
                'benefits' => ['Buku Cetak Fisik', 'Studi Kasus Lengkap'],
                'includes' => ['Pengiriman Buku'],
                'is_popular' => true,
            ],
        ];

        foreach ($courses as $course) {
            Course::create($course);
        }
    }
}
